class Surah {
  final String name;
  final String nameArabic;
  final String nameTranslation;
  final String revelationType;
  final int numberOfAyahs;

  Surah({
    required this.nameArabic,
    required this.name,
    required this.nameTranslation,
    required this.revelationType,
    required this.numberOfAyahs,
  });

  final List<Surah> surahs = [
    Surah(
      nameArabic: 'الفاتحة',
      name: 'Al-Fatihah',
      nameTranslation: 'The Opening',
      revelationType: 'Meccan',
      numberOfAyahs: 7,
    ),
    Surah(
      nameArabic: 'البقرة',
      name: 'Al-Baqarah',
      nameTranslation: 'The Cow',
      revelationType: 'Medinan',
      numberOfAyahs: 286,
    ),
    Surah(
      nameArabic: 'آل عمران',
      name: 'Al-Imran',
      nameTranslation: 'The Family of Imran',
      revelationType: 'Meccan',
      numberOfAyahs: 200,
    ),
    Surah(
      nameArabic: 'النساء',
      name: 'An-Nisa',
      nameTranslation: 'The Woman',
      revelationType: 'Medinan',
      numberOfAyahs: 77,
    ),
    Surah(
      nameArabic: 'النبإ',
      name: 'An-Naba',
      nameTranslation: 'The Clear Evidence',
      revelationType: 'Meccan',
      numberOfAyahs: 40,
    ),
    Surah(
      nameArabic: 'النازعات',
      name: 'An-Naziat',
      nameTranslation: 'The Hidden Evidence',
      revelationType: 'Meccan',
      numberOfAyahs: 46,
    ),
    Surah(
      nameArabic: 'عبس',
      name: 'Abasa',
      nameTranslation: 'He frowned',
      revelationType: 'Meccan',
      numberOfAyahs: 42,
    ),
    Surah(
      nameArabic: 'التكوير',
      name: 'At-Takwir',
      nameTranslation: 'The Overwhelming',
      revelationType: 'Meccan',
      numberOfAyahs: 29,
    ),
    Surah(
      nameArabic: 'الإنفطار',
      name: 'Al-Infitar',
      nameTranslation: 'The Cleaving',
      revelationType: 'Meccan',
      numberOfAyahs: 19,
    ),
    Surah(
      nameArabic: 'المطففين',
      name: 'Al-Mutaffifin',
      nameTranslation: 'Defrauding',
      revelationType: 'Meccan',
      numberOfAyahs: 36,
    ),
    Surah(
      nameArabic: 'الإنشقاق',
      name: 'Al-Inshiqaq',
      nameTranslation: 'The Splitting Open',
      revelationType: 'Meccan',
      numberOfAyahs: 25,
    ),
    Surah(
      nameArabic: 'البروج',
      name: 'Al-Burooj',
      nameTranslation: 'The Constrictor',
      revelationType: 'Meccan',
      numberOfAyahs: 22,
    ),
    Surah(
      nameArabic: 'الطارق',
      name: 'At-Tariq',
      nameTranslation: 'The Compiler',
      revelationType: 'Meccan',
      numberOfAyahs: 17,
    ),
    Surah(
      nameArabic: 'الأعلى',
      name: 'Al-Ala',
      nameTranslation: 'The Most High',
      revelationType: 'Meccan',
      numberOfAyahs: 19,
    ),
    Surah(
      nameArabic: 'الغاشية',
      name: 'Al-Ghashiyah',
      nameTranslation: 'The Overwhelming',
      revelationType: 'Meccan',
      numberOfAyahs: 26,
    ),
    Surah(
      nameArabic: 'الفجر',
      name: 'Al-Fajr',
      nameTranslation: 'The Dawn',
      revelationType: 'Meccan',
      numberOfAyahs: 30,
    ),
    Surah(
      nameArabic: 'البلد',
      name: 'Al-Balad',
      nameTranslation: 'The City',
      revelationType: 'Meccan',
      numberOfAyahs: 20,
    ),
    Surah(
      nameArabic: 'الشمس',
      name: 'Ash-Shams',
      nameTranslation: 'The Sun',
      revelationType: 'Meccan',
      numberOfAyahs: 15,
    ),
    Surah(
      nameArabic: 'الليل',
      name: 'Al-Lail',
      nameTranslation: 'The Night',
      revelationType: 'Meccan',
      numberOfAyahs: 21,
    ),
    Surah(
      nameArabic: 'الضحى',
      name: 'Ad-Dhuha',
      nameTranslation: 'The Morning Hours',
      revelationType: 'Meccan',
      numberOfAyahs: 11,
    ),
    Surah(
      nameArabic: 'الشرح',
      name: 'Ash-Sharh',
      nameTranslation: 'The Consolation',
      revelationType: 'Meccan',
      numberOfAyahs: 8,
    ),
    Surah(
      nameArabic: 'التين',
      name: 'At-Teen',
      nameTranslation: 'The Fig',
      revelationType: 'Meccan',
      numberOfAyahs: 8,
    ),
    Surah(
      nameArabic: 'العلق',
      name: 'Al-Alaq',
      nameTranslation: 'The Clot',
      revelationType: 'Meccan',
      numberOfAyahs: 19,
    ),
    Surah(
      nameArabic: 'القدر',
      name: 'Al-Qadr',
      nameTranslation: 'The Power, Fate',
      revelationType: 'Meccan',
      numberOfAyahs: 5,
    ),
    Surah(
      nameArabic: 'البينة',
      name: 'Al-Bayyina',
      nameTranslation: 'The Evidence',
      revelationType: 'Medinan',
      numberOfAyahs: 8,
    ),
    Surah(
      nameArabic: 'الزلزلة',
      name: 'Az-Zalzala',
      nameTranslation: 'The Earthquake',
      revelationType: 'Medinan',
      numberOfAyahs: 8,
    ),
    Surah(
      nameArabic: 'العاديات',
      name: 'Al-Aadiyaat',
      nameTranslation: 'The Chargers',
      revelationType: 'Meccan',
      numberOfAyahs: 11,
    ),
    Surah(
      nameArabic: 'القارعة',
      name: 'Al-Qaria',
      nameTranslation: 'The Calamity',
      revelationType: 'Meccan',
      numberOfAyahs: 11,
    ),
    Surah(
      nameArabic: 'التكاثر',
      name: 'At-Takaathur',
      nameTranslation: 'Competition',
      revelationType: 'Meccan',
      numberOfAyahs: 8,
    ),
    Surah(
      nameArabic: 'العصر',
      name: 'Al-Asr',
      nameTranslation: 'The Declining Day',
      revelationType: 'Meccan',
      numberOfAyahs: 3,
    ),
    Surah(
      nameArabic: 'الهمزة',
      name: 'Al-Humaza',
      nameTranslation: 'The Traducer',
      revelationType: 'Meccan',
      numberOfAyahs: 9,
    ),
    Surah(
      nameArabic: 'الفيل',
      name: 'Al-Fil',
      nameTranslation: 'The Elephant',
      revelationType: 'Meccan',
      numberOfAyahs: 5,
    ),
    Surah(
      nameArabic: 'قريش',
      name: 'Quraish',
      nameTranslation: 'Quraysh',
      revelationType: 'Meccan',
      numberOfAyahs: 4,
    ),
    Surah(
      nameArabic: 'الماعون',
      name: 'Al-Maun',
      nameTranslation: 'Almsgiving',
      revelationType: 'Meccan',
      numberOfAyahs: 7,
    ),
    Surah(
      nameArabic: 'الكوثر',
      name: 'Al-Kawthar',
      nameTranslation: 'Abundance',
      revelationType: 'Meccan',
      numberOfAyahs: 3,
    ),
    Surah(
      nameArabic: 'الكافرون',
      name: 'Al-Kaafiroon',
      nameTranslation: 'The Disbelievers',
      revelationType: 'Meccan',
      numberOfAyahs: 6,
    ),
    Surah(
      nameArabic: 'النصر',
      name: 'An-Nasr',
      nameTranslation: 'Divine Support',
      revelationType: 'Medinan',
      numberOfAyahs: 3,
    ),
    Surah(
      nameArabic: 'المسد',
      name: 'Al-Masad',
      nameTranslation: 'The Palm Fibre',
      revelationType: 'Meccan',
      numberOfAyahs: 5,
    ),
    Surah(
      nameArabic: 'الإخلاص',
      name: 'Al-Ikhlas',
      nameTranslation: 'Sincerity',
      revelationType: 'Meccan',
      numberOfAyahs: 4,
    ),
    Surah(
      nameArabic: 'الفلق',
      name: 'Al-Falaq',
      nameTranslation: 'The Dawn',
      revelationType: 'Meccan',
      numberOfAyahs: 5,
    ),
    Surah(
      nameArabic: 'الناس',
      name: 'An-Nas',
      nameTranslation: 'Mankind',
      revelationType: 'Meccan',
      numberOfAyahs: 6,
    ),
  ];
}
